name = "nextjs-starter"
compatibility_date = "2024-12-01"

pages_build_output_dir = ".vercel/output/static"

compatibility_flags = [
  "nodejs_compat"
]

[build]
command = "npx @cloudflare/next-on-pages"

